# Generated by Django 4.2.15 on 2025-08-08 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brokers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartbeatStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_connected', models.BooleanField(default=False)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('symbols_monitored', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Etat du Heartbeat',
                'verbose_name_plural': 'Etats du Heartbeat',
                'db_table': 'heartbeat_status',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('side', models.CharField(choices=[('buy', 'Achat'), ('sell', 'Vente')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('current_price', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('stop_loss', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('take_profit', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('unrealized_pnl', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('realized_pnl', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('closing', 'En cours de fermeture'), ('closed', 'Fermee')], default='open', max_length=20)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brokers.broker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'positions',
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='positions_user_id_7b75ed_idx'), models.Index(fields=['broker', 'symbol'], name='positions_broker__d3e370_idx')],
            },
        ),
    ]
