# Generated by Django 4.2.15 on 2025-08-11 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heartbeatstatus',
            name='last_application_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heartbeatstatus',
            name='last_application_stop',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CandleHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dhm_reception', models.DateTimeField()),
                ('dhm_candle', models.DateTimeField()),
                ('signal_type', models.CharField(choices=[('1m', '1 minute'), ('3m', '3 minutes'), ('5m', '5 minutes'), ('15m', '15 minutes'), ('1h', '1 heure'), ('4h', '4 heures')], max_length=10)),
                ('symbol', models.CharField(default='BTCUSDT', max_length=20)),
                ('open_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('high_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('heartbeat_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candle_signals', to='core.heartbeatstatus')),
            ],
            options={
                'verbose_name': 'Signal Heartbeat',
                'verbose_name_plural': 'Signaux Heartbeat',
                'db_table': 'candles_heartbeat',
                'ordering': ['-dhm_candle'],
                'indexes': [models.Index(fields=['signal_type', '-dhm_candle'], name='candles_hea_signal__261713_idx'), models.Index(fields=['symbol', 'signal_type'], name='candles_hea_symbol_8c28ec_idx')],
            },
        ),
    ]
