# Generated by Django 4.2.15 on 2026-03-02 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('code', models.TextField()),
                ('timeframe', models.CharField(choices=[('1m', '1 minute'), ('3m', '3 minutes'), ('5m', '5 minutes'), ('15m', '15 minutes'), ('1h', '1 heure'), ('4h', '4 heures')], default='15m', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Strategie',
                'verbose_name_plural': 'Strategies',
                'db_table': 'strategies',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'timeframe'], name='strategies_user_id_2ffbdf_idx')],
            },
        ),
    ]
