# Generated by Django 4.2.15 on 2025-08-12 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brokers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('manual', 'Trading Manuel'), ('webhook', 'Webhook TradingView'), ('strategy', 'Strategie Automatique'), ('backtest', 'Backtest')], default='manual', max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('side', models.CharField(choices=[('buy', 'Achat'), ('sell', 'Vente')], max_length=4)),
                ('order_type', models.CharField(choices=[('market', 'Marche'), ('limit', 'Limite')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('total_value', models.DecimalField(decimal_places=8, max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('filled', 'Execute'), ('cancelled', 'Annule'), ('failed', 'Echec')], default='pending', max_length=10)),
                ('filled_quantity', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('filled_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('fees', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('exchange_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brokers.broker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'broker', 'symbol'], name='trading_man_user_id_5a208f_idx'), models.Index(fields=['user', 'trade_type', 'status'], name='trading_man_user_id_75f165_idx'), models.Index(fields=['created_at'], name='trading_man_created_2af229_idx')],
            },
        ),
    ]
