# Generated by Django 4.2.15 on 2025-08-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_manual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='stop_loss_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='take_profit_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='trigger_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='order_type',
            field=models.CharField(choices=[('market', 'Marche'), ('limit', 'Limite'), ('stop_loss', 'Stop Loss'), ('take_profit', 'Take Profit'), ('sl_tp_combo', 'Stop Loss + Take Profit'), ('stop_limit', 'Stop Limite')], max_length=15),
        ),
    ]
