# Generated by Django 4.2.15 on 2025-09-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_manual', '0002_trade_stop_loss_price_trade_take_profit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='avg_buy_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='exchange_client_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='exchange_order_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='pnl_calculation_method',
            field=models.CharField(choices=[('none', 'Aucun'), ('manual', 'Manuel'), ('price_averaging', 'Prix Moyen'), ('fifo', 'FIFO'), ('user_choice', 'Choix Utilisateur')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='trade',
            name='position_quantity_after',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='raw_order_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='realized_pnl',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='source',
            field=models.CharField(choices=[('manual', 'Saisie Manuelle'), ('trading_manual', 'Trading Manuel'), ('webhook', 'Webhook'), ('strategy', 'Strategie'), ('terminal7', 'Terminal 7'), ('backtest', 'Backtest')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('filled', 'Execute'), ('cancelled', 'Annule'), ('failed', 'Echec'), ('completed', 'Termine')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_type',
            field=models.CharField(choices=[('manual', 'Trading Manuel'), ('webhook', 'Webhook TradingView'), ('strategy', 'Strategie Automatique'), ('backtest', 'Backtest'), ('terminal7', 'Terminal 7 (Auto-detection)')], default='manual', max_length=20),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['source'], name='trading_man_source_da47cc_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['exchange_order_id'], name='trading_man_exchang_b65f07_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['executed_at'], name='trading_man_execute_fabe9e_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['user', 'broker', 'symbol', 'side'], name='trading_man_user_id_22225f_idx'),
        ),
    ]
