# Generated by Django 4.2.15 on 2025-09-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_manual', '0003_trade_avg_buy_price_trade_exchange_client_order_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['user', 'broker', '-created_at'], name='trading_man_user_id_1cc032_idx'),
        ),
    ]
