# Generated by Django 4.2.15 on 2025-09-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_manual', '0004_trade_trading_man_user_id_1cc032_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='cancel_reason',
            field=models.CharField(blank=True, choices=[('normal_cancel', 'Normal Cancel'), ('stp_cancel', 'Cancelled by STP')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='enter_point_source',
            field=models.CharField(blank=True, choices=[('WEB', 'Web Client'), ('APP', 'App Client'), ('API', 'API Client'), ('SYS', 'System Client'), ('ANDROID', 'Android Client'), ('IOS', 'iOS Client')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='exchange_raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='exchange_user_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='execute_stop_loss_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='execute_take_profit_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='fee_detail',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='force',
            field=models.CharField(blank=True, choices=[('GTC', 'Good Till Cancel'), ('FOK', 'Fill or Kill'), ('IOC', 'Immediate or Cancel'), ('post_only', 'Post Only')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='order_source',
            field=models.CharField(blank=True, choices=[('normal', 'Normal Order'), ('market', 'Market Order'), ('spot_trader_buy', 'Elite Spot Trade Buy'), ('spot_follower_buy', 'Copy Trade Buy'), ('spot_trader_sell', 'Elite Spot Trade Sell'), ('spot_follower_sell', 'Copy Trade Sell'), ('strategy_oco_limit', 'OCO Orders')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='ordre_existant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='preset_stop_loss_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='preset_take_profit_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='quote_volume',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='stp_mode',
            field=models.CharField(blank=True, choices=[('none', 'No STP'), ('cancel_taker', 'Cancel Taker'), ('cancel_maker', 'Cancel Maker'), ('cancel_both', 'Cancel Both')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='tpsl_type',
            field=models.CharField(blank=True, choices=[('normal', 'Spot Order'), ('tpsl', 'Spot TPSL Order')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='trade_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='trade_scope',
            field=models.CharField(blank=True, choices=[('taker', 'Taker'), ('maker', 'Maker')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['ordre_existant'], name='trading_man_ordre_e_4ab8ee_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['enter_point_source'], name='trading_man_enter_p_fe2402_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['trade_id'], name='trading_man_trade_i_3a7d1b_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['exchange_user_id'], name='trading_man_exchang_5fbc4a_idx'),
        ),
    ]
