# Generated by Django 4.2.15 on 2026-01-23 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('exchange_name', models.CharField(blank=True, max_length=50)),
                ('interval', models.CharField(max_length=10)),
                ('action', models.CharField(choices=[('PING', 'Ping (heartbeat)'), ('BuyMarket', 'Achat marche'), ('SellMarket', 'Vente marche'), ('BuyLimit', 'Achat limite'), ('SellLimit', 'Vente limite'), ('MAJ', 'Mise a jour SL/TP'), ('MISS', 'Signal manquant')], max_length=20)),
                ('prix', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('prix_sl', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('prix_tp', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('pour_cent', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('status', models.CharField(choices=[('received', 'Recu'), ('processing', 'En traitement'), ('processed', 'Traite'), ('error', 'Erreur'), ('miss', 'Manquant')], default='received', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('bar_time', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('order_id', models.CharField(blank=True, max_length=128)),
                ('execution_result', models.JSONField(blank=True, null=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='brokers.broker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Webhook',
                'verbose_name_plural': 'Webhooks',
                'db_table': 'webhooks',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('closed', 'Fermee')], default='open', max_length=20)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('side', models.CharField(max_length=10)),
                ('current_sl', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('current_tp', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('sl_order_id', models.CharField(blank=True, max_length=128)),
                ('tp_order_id', models.CharField(blank=True, max_length=128)),
                ('unrealized_pnl', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('realized_pnl', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_states', to='brokers.broker')),
                ('opening_webhook', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_positions', to='webhooks.webhook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Etat Position Webhook',
                'verbose_name_plural': 'Etats Positions Webhooks',
                'db_table': 'webhook_states',
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['user', 'broker', 'symbol', 'status'], name='webhook_sta_user_id_ef7613_idx'), models.Index(fields=['status', '-opened_at'], name='webhook_sta_status_e53bd1_idx')],
                'unique_together': {('user', 'broker', 'symbol', 'status')},
            },
        ),
        migrations.AddIndex(
            model_name='webhook',
            index=models.Index(fields=['user', 'status'], name='webhooks_user_id_38bbbe_idx'),
        ),
        migrations.AddIndex(
            model_name='webhook',
            index=models.Index(fields=['broker', 'symbol'], name='webhooks_broker__b2f5e4_idx'),
        ),
        migrations.AddIndex(
            model_name='webhook',
            index=models.Index(fields=['action', 'received_at'], name='webhooks_action_9214b5_idx'),
        ),
        migrations.AddIndex(
            model_name='webhook',
            index=models.Index(fields=['-received_at'], name='webhooks_receive_b3e68b_idx'),
        ),
    ]
