# Generated by Django 4.2.15 on 2026-03-02 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai_model',
            field=models.CharField(blank=True, default='', help_text='Modele IA a utiliser (ex: gpt-4o-mini, llama3:8b)', max_length=100),
        ),
    ]
