# Generated by Django 4.2.15 on 2026-03-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_ai_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai_generate_prompt',
            field=models.TextField(blank=True, default='', help_text='Pre-prompt personnalise pour le mode Generer (admin uniquement)'),
        ),
    ]
