# Generated by Django 4.2.15 on 2026-03-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_ai_generate_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai_continue_prompt',
            field=models.TextField(blank=True, default='', help_text='Pre-prompt personnalise pour le mode Continuer (admin uniquement)'),
        ),
    ]
