# Generated by Django 4.2.15 on 2025-08-08 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(db_index=True, max_length=50)),
                ('symbol', models.CharField(help_text='Symbol unifie CCXT (ex: BTC/USDT)', max_length=50)),
                ('base', models.CharField(max_length=20)),
                ('quote', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('spot', 'Spot'), ('future', 'Future'), ('swap', 'Swap'), ('option', 'Option')], default='spot', max_length=20)),
                ('min_amount', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('max_amount', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('min_price', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('max_price', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('min_cost', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('amount_precision', models.IntegerField(null=True)),
                ('price_precision', models.IntegerField(null=True)),
                ('raw_info', models.JSONField(blank=True, default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exchange_symbols',
                'ordering': ['exchange', 'symbol'],
                'indexes': [models.Index(fields=['exchange', 'active'], name='exchange_sy_exchang_c340e2_idx'), models.Index(fields=['symbol'], name='exchange_sy_symbol_2a2245_idx')],
                'unique_together': {('exchange', 'symbol', 'type')},
            },
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(choices=[('binance', 'Binance'), ('binanceus', 'Binance US'), ('kraken', 'Kraken'), ('coinbase', 'Coinbase'), ('kucoin', 'KuCoin'), ('bitget', 'Bitget'), ('okx', 'OKX'), ('bybit', 'Bybit'), ('gateio', 'Gate.io'), ('mexc', 'MEXC')], max_length=50)),
                ('name', models.CharField(help_text='Nom personnalise (ex: Binance Principal)', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('api_key', models.TextField()),
                ('api_secret', models.TextField()),
                ('api_password', models.TextField(blank=True, null=True)),
                ('subaccount_name', models.CharField(blank=True, help_text='Nom du sous-compte si applicable', max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('is_testnet', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_connection_test', models.DateTimeField(blank=True, null=True)),
                ('last_connection_success', models.BooleanField(default=False)),
                ('last_balance_update', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brokers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Broker',
                'verbose_name_plural': 'Brokers',
                'db_table': 'brokers',
                'ordering': ['-is_default', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
