# Generated by Django 4.2.15 on 2026-01-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='type_de_trading',
            field=models.CharField(choices=[('OFF', 'Desactive'), ('Strategie', 'Strategies automatiques'), ('Webhooks', 'Webhooks TradingView')], default='OFF', help_text='Mode de trading autorise pour ce broker', max_length=20),
        ),
    ]
