# Generated by Django 4.2.15 on 2025-08-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DebugMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, help_text="Mode debug actif (permet auto-login avec 'dev')")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mode Debug',
                'verbose_name_plural': 'Mode Debug',
                'db_table': 'debug_mode',
            },
        ),
    ]
